#define WIN32_LEAN_AND_MEAN
#include "Graphics.h"
#include "UIView.h"
#include "UIImage.h"

#include "UIMenu.h"
#include "UIButton.h"
#include "UILabel.h"
#include "UITextbox.h"
#include "UICircularProgressBar.h"
#include "UIProgressBar.h"
#include "UICheckbox.h"
#include "UISlider.h"
#include "UIScrollPanel.h"
#include "UICombobox.h"

#include "Color.h"
#include "UIFileChooser.h"
#include "Mouse.h"
#include "Keyboard.hpp"